<?php

namespace Database\Seeders;

use App\Models\AgencyProfile;
use App\Models\Property;
use App\Models\PropertyImage;
use App\Models\User;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Agences Agréées
        $agency1 = AgencyProfile::create([
            'name' => 'Dakar Prestige Immobilier',
            'slug' => 'dakar-prestige-immobilier',
            'logo_url' => 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=200&q=80',
            'phone_whatsapp' => '+221 77 845 12 34',
            'email' => 'contact@dakarprestige.sn',
            'city' => 'Dakar',
            'address' => 'Route des Almadies, Dakar',
            'description' => 'Agence certifiée Izivilla numéro 1 sur les appartements meublés et villas de standing à Dakar.',
            'is_verified' => true,
            'active_listings_count' => 12,
            'subscription_tier' => 'Pro',
        ]);

        $agency2 = AgencyProfile::create([
            'name' => 'Immo Conseil Sénégal',
            'slug' => 'immo-conseil-senegal',
            'logo_url' => 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=200&q=80',
            'phone_whatsapp' => '+221 78 120 45 67',
            'email' => 'contact@immoconseil.sn',
            'city' => 'Dakar',
            'address' => 'Immeuble VDN 2, Mermoz, Dakar',
            'description' => 'Agence agréée spécialisée dans les biens résidentiels et locaux commerciaux.',
            'is_verified' => true,
            'active_listings_count' => 8,
            'subscription_tier' => 'Enterprise',
        ]);

        // 2. Real Izivilla Database Properties across all categories
        $propertiesData = [
            [
                'agency_profile_id' => null,
                'title' => 'Villa Contemporaine 5 Chambres avec Piscine aux Almadies',
                'slug' => 'villa-contemporaine-5-chambres-piscine-almadies',
                'description' => 'Magnifique villa contemporaine située au cœur des Almadies. Comprend 5 grandes chambres autonomes, grand séjour baigné de lumière, cuisine équipée moderne, jardin avec piscine privée, garage 2 voitures et poste de garde 24h/24. Annonce directe de particulier à particulier.',
                'property_type' => 'Villa',
                'transaction_type' => 'sale',
                'price_fcfa' => 350000000,
                'charges_included' => true,
                'city' => 'Dakar',
                'quartier' => 'Almadies',
                'bedrooms' => 5,
                'bathrooms' => 4,
                'surface_sqm' => 450,
                'is_furnished' => true,
                'has_air_con' => true,
                'has_generator' => true,
                'has_security' => true,
                'has_parking' => true,
                'has_pool' => true,
                'equipments' => ['Piscine', 'Groupe Électrogène', 'Caméras Sécurité', 'Bassin d\'eau', 'Smart Home'],
                'latitude' => 14.7454,
                'longitude' => -17.5194,
                'status' => 'available',
                'is_featured' => true,
                'is_boosted' => true,
                'views_count' => 1420,
                'owner_type' => 'Propriétaire',
                'owner_name' => 'Amadou Sow',
                'owner_phone' => '+221 77 645 12 34',
                'owner_email' => 'amadou.sow@izivilla.sn',
                'is_verified' => true,
                'contact_phone' => '+221 77 645 12 34',
                'contact_whatsapp' => '+221 77 645 12 34',
                'images' => [
                    'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
                ]
            ],
            [
                'agency_profile_id' => $agency2->id,
                'title' => 'Appartement Haut Standing F4 avec Balcon Vue Mer à Mermoz',
                'slug' => 'appartement-haut-standing-f4-vue-mer-mermoz',
                'description' => 'Superbe appartement F4 neuf dans un immeuble récent avec ascenseur à Mermoz VDN. Salon spacieux, 3 chambres climatisées avec dressing, balcon panoramique, cuisine américaine.',
                'property_type' => 'Appartement',
                'transaction_type' => 'rent',
                'price_fcfa' => 750000,
                'charges_included' => true,
                'city' => 'Dakar',
                'quartier' => 'Mermoz',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'surface_sqm' => 165,
                'is_furnished' => false,
                'has_air_con' => true,
                'has_generator' => true,
                'has_security' => true,
                'has_parking' => true,
                'has_pool' => false,
                'equipments' => ['Ascenseur', 'Surveillance 24h/7d', 'Parking Sous-sol', 'Groupe Réserve'],
                'latitude' => 14.7081,
                'longitude' => -17.4697,
                'status' => 'available',
                'is_featured' => true,
                'is_boosted' => true,
                'views_count' => 980,
                'owner_type' => 'Agence',
                'owner_name' => 'Immo Conseil Sénégal',
                'owner_phone' => '+221 33 869 40 40',
                'owner_email' => 'contact@immoconseil.sn',
                'is_verified' => true,
                'contact_phone' => '+221 33 869 40 40',
                'contact_whatsapp' => '+221 78 120 45 67',
                'images' => [
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80',
                ]
            ],
            [
                'agency_profile_id' => null,
                'title' => 'Studio Cosy Meublé avec Wi-Fi & Smart TV à Sacré-Cœur 3',
                'slug' => 'studio-cosy-meuble-sacre-coeur-3',
                'description' => 'Studio indépendant moderne et parfaitement équipé à Sacré-Cœur 3. Idéal pour professionnels ou séjours courts. Wi-Fi haut débit, ménage inclus 2x/semaine.',
                'property_type' => 'Studio',
                'transaction_type' => 'rent',
                'price_fcfa' => 280000,
                'charges_included' => true,
                'city' => 'Dakar',
                'quartier' => 'Sacré-Cœur',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'surface_sqm' => 42,
                'is_furnished' => true,
                'has_air_con' => true,
                'has_generator' => true,
                'has_security' => true,
                'has_parking' => false,
                'has_pool' => false,
                'equipments' => ['Wi-Fi inclus', 'Canal+', 'Micro-ondes', 'Refrigérateur'],
                'latitude' => 14.7180,
                'longitude' => -17.4720,
                'status' => 'available',
                'is_featured' => false,
                'is_boosted' => false,
                'views_count' => 640,
                'owner_type' => 'Propriétaire',
                'owner_name' => 'Fatou Kiné Ba',
                'owner_phone' => '+221 77 312 88 99',
                'owner_email' => 'fatoukine.ba@izivilla.sn',
                'is_verified' => true,
                'contact_phone' => '+221 77 312 88 99',
                'contact_whatsapp' => '+221 77 312 88 99',
                'images' => [
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
                ]
            ],
            [
                'agency_profile_id' => null,
                'title' => 'Terrain Viabilisé Pieds dans l\'Eau de 600m² à Saly Portudal',
                'slug' => 'terrain-viabilise-600m2-saly-portudal',
                'description' => 'Magnifique parcelle de terrain à bâtir avec titre foncier individuel. Emplacement exceptionnel proche mer à Saly Portudal. Eau, électricité et accès goudronné immédiats.',
                'property_type' => 'Terrain',
                'transaction_type' => 'sale',
                'price_fcfa' => 65000000,
                'charges_included' => false,
                'city' => 'Saly',
                'quartier' => 'Saly Portudal',
                'bedrooms' => 0,
                'bathrooms' => 0,
                'surface_sqm' => 600,
                'is_furnished' => false,
                'has_air_con' => false,
                'has_generator' => false,
                'has_security' => false,
                'has_parking' => false,
                'has_pool' => false,
                'equipments' => ['Titre Foncier', 'Eau Onas', 'Senelec', 'Vue Mer'],
                'latitude' => 14.4447,
                'longitude' => -17.0094,
                'status' => 'available',
                'is_featured' => true,
                'is_boosted' => true,
                'views_count' => 2100,
                'owner_type' => 'Propriétaire',
                'owner_name' => 'Babacar Ndiaye',
                'owner_phone' => '+221 70 888 77 66',
                'owner_email' => 'babacar.ndiaye@izivilla.sn',
                'is_verified' => true,
                'contact_phone' => '+221 70 888 77 66',
                'contact_whatsapp' => '+221 70 888 77 66',
                'images' => [
                    'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
                ]
            ],
            [
                'agency_profile_id' => $agency1->id,
                'title' => 'Plateau de Bureaux Modernes 250m² sur l\'Avenue VDN',
                'slug' => 'plateau-de-bureaux-modernes-250m2-vdn',
                'description' => 'Espace commercial et bureaux aménagés au 3ème étage d\'un immeuble d\'affaires très prisé sur la VDN. Fibre optique, climatisation centrale, parking privé.',
                'property_type' => 'Bureau',
                'transaction_type' => 'rent',
                'price_fcfa' => 1800000,
                'charges_included' => true,
                'city' => 'Dakar',
                'quartier' => 'Ouakam',
                'bedrooms' => 0,
                'bathrooms' => 2,
                'surface_sqm' => 250,
                'is_furnished' => false,
                'has_air_con' => true,
                'has_generator' => true,
                'has_security' => true,
                'has_parking' => true,
                'has_pool' => false,
                'equipments' => ['Fibre Optique', 'Groupes 250kVA', 'Gardiennage 24/7'],
                'latitude' => 14.7230,
                'longitude' => -17.4750,
                'status' => 'available',
                'is_featured' => false,
                'is_boosted' => false,
                'views_count' => 530,
                'owner_type' => 'Agence',
                'owner_name' => 'Dakar Prestige Immobilier',
                'owner_phone' => '+221 77 845 12 34',
                'owner_email' => 'contact@dakarprestige.sn',
                'is_verified' => true,
                'contact_phone' => '+221 77 845 12 34',
                'contact_whatsapp' => '+221 77 845 12 34',
                'images' => [
                    'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
                ]
            ],
            [
                'agency_profile_id' => null,
                'title' => 'Local Commercial & Boutique d\'Angle sur l\'Avenue Cheikh Anta Diop',
                'slug' => 'local-commercial-boutique-avenue-cheikh-anta-diop',
                'description' => 'Emplacement commercial de premier ordre à Fann Point E. Idéal pour showroom, banque, franchise ou boutique de luxe. Grande vitrine, forte visibilité.',
                'property_type' => 'Bureau',
                'transaction_type' => 'rent',
                'price_fcfa' => 1200000,
                'charges_included' => true,
                'city' => 'Dakar',
                'quartier' => 'Fann Point E',
                'bedrooms' => 0,
                'bathrooms' => 1,
                'surface_sqm' => 120,
                'is_furnished' => false,
                'has_air_con' => true,
                'has_generator' => true,
                'has_security' => true,
                'has_parking' => true,
                'has_pool' => false,
                'equipments' => ['Vitrine Sécurisée', 'Climatisation', 'Compteur Woyofal'],
                'latitude' => 14.6850,
                'longitude' => -17.4620,
                'status' => 'available',
                'is_featured' => true,
                'is_boosted' => true,
                'views_count' => 840,
                'owner_type' => 'Propriétaire',
                'owner_name' => 'Moussa Ndiaye',
                'owner_phone' => '+221 77 500 22 33',
                'owner_email' => 'moussa.ndiaye@izivilla.sn',
                'is_verified' => true,
                'contact_phone' => '+221 77 500 22 33',
                'contact_whatsapp' => '+221 77 500 22 33',
                'images' => [
                    'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
                ]
            ],
            [
                'agency_profile_id' => null,
                'title' => 'Maison Familiale R+1 avec Cour et Garage aux Parcelles Assainies',
                'slug' => 'maison-familiale-r-1-parcelles-assainies',
                'description' => 'Superbe maison familiale en vente aux Parcelles Assainies Unité 15. 4 chambres, salon spacieux, cuisine, réserve d\'eau et garage fermé.',
                'property_type' => 'Maison',
                'transaction_type' => 'sale',
                'price_fcfa' => 85000000,
                'charges_included' => false,
                'city' => 'Dakar',
                'quartier' => 'Parcelles Assainies',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'surface_sqm' => 200,
                'is_furnished' => false,
                'has_air_con' => false,
                'has_generator' => false,
                'has_security' => true,
                'has_parking' => true,
                'has_pool' => false,
                'equipments' => ['Cour Intérieure', 'Réservoir d\'eau', 'Garage'],
                'latitude' => 14.7550,
                'longitude' => -17.4350,
                'status' => 'available',
                'is_featured' => false,
                'is_boosted' => false,
                'views_count' => 410,
                'owner_type' => 'Propriétaire',
                'owner_name' => 'Ousmane Fall',
                'owner_phone' => '+221 76 500 11 22',
                'owner_email' => 'ousmane.fall@izivilla.sn',
                'is_verified' => true,
                'contact_phone' => '+221 76 500 11 22',
                'contact_whatsapp' => '+221 76 500 11 22',
                'images' => [
                    'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80',
                ]
            ]
        ];

        foreach ($propertiesData as $pData) {
            $images = $pData['images'];
            unset($pData['images']);

            $prop = Property::create($pData);

            foreach ($images as $idx => $imgUrl) {
                PropertyImage::create([
                    'property_id' => $prop->id,
                    'image_url' => $imgUrl,
                    'is_primary' => $idx === 0,
                ]);
            }
        }
    }
}
